### ISSUE TITLE
Why pass `2`?

### ISSUE THREAD

**Issue by shakhbulatgaz** [markalfred/eslint-plugin-no-constructor-bind#26]
Why do we have to pass write the rule like `"no-constructor-bind/no-constructor-bind": 2,`?
Why the value "2"?

**Comment by markalfred** [comment]
Hi @shakhbulatgaz, "2" is used by ESLint as a shorthand for "error". That said, using the shorthand in a readme is never the right way to do it, so I'm going to update.

> ESLint comes with a large number of rules. You can modify which rules your project uses either using configuration comments or configuration files. To change a rule setting, you must set the rule ID equal to one of these values:
>
> "off" or 0 - turn the rule off
> "warn" or 1 - turn the rule on as a warning (doesn’t affect exit code)
> "error" or 2 - turn the rule on as an error (exit code is 1 when triggered)

https://eslint.org/docs/user-guide/configuring#configuring-rules

**Comment by shakhbulatgaz** [comment]
Oh, I see, sorry. 
Thank you for your quick answer!
