### ISSUE TITLE
TypeError: Cannot read property 'name' of undefined

### ISSUE THREAD

**Issue by vikas-bansal-DisneyPH** [markalfred/eslint-plugin-no-constructor-bind#46]
Hi Bro,

I am back with another issue :D :P 

```
class CanvasChart extends PureComponent {
  constructor(props) {
    super(props);
    this.xyz = xyz.bind(this);
  }
}
```

while fixing the above code it gives the following error
```

TypeError: Cannot read property 'name' of undefined
Occurred while linting /Users/vikasbansal/Desktop/work/stats-for-nerds/src/components/canvas-chart.js:11
```

What I could suggest is that if the function is not defined in the class the plugin should ignore it and move forward.

Thanks for making dev's life easy by investing time building such beautiful utils @markalfred

**Comment by markalfred** [comment]
Thanks for submitting this @vikas-bansal-DisneyPH! 🙇 

I'm batting around the idea that either your example code should be treated as invalid and fixed, or treated as valid. Either way, the plugin definitely shouldn't be crashing!

I believe your example code _could_ be "fixed" to the following:

```js
class CanvasChart extends PureComponent {
  constructor(props) {
    super(props)
  }

  xyz = xyz
}
```

Let me think a bit more about it and I'll push up a fix shortly. Thanks again for all your contributions 🙂

**Comment by vikas-bansal-DisneyPH** [comment]
thanks for quick reply @markalfred 

```
class CanvasChart extends PureComponent {
  constructor(props) {
    super(props)
  }

  xyz = xyz
}
```

doing the above won't bind the `xyz` with the context of the instance of the class which will cause unexpected results.

**Comment by markalfred** [comment]
It won't if `xyz` is an arrow function, but it will if it's a `function` — which is equivalent to how the `.bind` call would work too...

```js
arrow = () => { return this }
function fn() { return this }

class Foo {
  constructor() {
    this.boundArrow = arrow.bind(this)
    this.boundFn = fn.bind(this)
  }
  
  propArrow = arrow
  propFn = fn
}

f = new Foo

[f.boundArrow(), f.boundFn(), f.propArrow(), f.propFn()]
// => [Window, Foo, Window, Foo]
```

It feels a little fraught for it to work this way, but the two are in fact functionally equivalent (as far as I can tell, anyway).

But zooming out a little bit, converting `this.xyz = xyz.bind` to `xyz = xyz` isn't a usecase that I originally had in mind for this plugin, so it's possible that it's outside the scope of its duties.

**Comment by vikas-bansal-DisneyPH** [comment]
I agree that this scenario can be skipped however the plugin should not crash.

but where the function is not a part of class and borrowed from some other resource, should be considered a violation of the rule or not?

**Comment by markalfred** [comment]
I can definitely see it going either way, but your vote is that it _should not_ be considered a violation, correct?

**Comment by vikas-bansal-DisneyPH** [comment]
I vote for to have another flag for this situation 😄 
`"no-constructor-bind/no-constructor-function-borrowing": "error"`

**Comment by markalfred** [comment]
This code is now considered "valid" in `v2.0.3`:

```js
class myClass { constructor() { this.myFunction = myFunction.bind(this) } }
```

Thanks again @vikas-bansal-DisneyPH :)

**Comment by vikas-bansal-DisneyPH** [comment]
Thanks @markalfred 😆
