### ISSUE TITLE
Crashes when member functions return anonymous classes

### ISSUE THREAD

**Issue by poteat** [markalfred/eslint-plugin-no-constructor-bind#48]
**This occurs at:** `node_modules/eslint-plugin-no-constructor-bind/lib/rules/no-constructor-bind.js:134:30`

**The error message is:** `TypeError: Cannot read property 'forEach' of undefined`

**My ESLint version is**: `7.12.0`

**My `eslint-plugin-no-constructor-bind` version is:** `2.0.3`

**The minimal reproducing code is:**

```ts
class X {
  x() {
    return class {}
  }
}
```

Thanks!

**Comment by markalfred** [comment]
Thanks for the code sample, @poteat, I'll take a look!

**Comment by markalfred** [comment]
@poteat feel free to give https://github.com/markalfred/eslint-plugin-no-constructor-bind/releases/tag/v2.0.4 a try and let me know if that fixes things for you. 👍
