### ISSUE TITLE
Using arrow class methods get more RAM, instead bind (when < es8)

### ISSUE THREAD

**Issue by denisx** [markalfred/eslint-plugin-no-constructor-bind#9]
Plz make mirror rule, to highlight arrow class methods, to convert them ti=o functions with a constructor *.bind

**Comment by markalfred** [comment]
@denisx this may better suit your usecase if used with the `'never'` option: https://github.com/Shopify/eslint-plugin-shopify/blob/master/docs/rules/prefer-class-properties.md
